tasks:
  - init: npm ci
    command: |
      export BUNDLE_REQUEST_URL="$(gp url 8081)/index.bundle?dev=true&minify=false"
      { gp await-port 8081 && sleep 5 && gp preview $BUNDLE_REQUEST_URL?platform=android & } &> /dev/null
      { gp await-port 8081 && sleep 5 && gp preview $BUNDLE_REQUEST_URL?platform=ios & } &> /dev/null
      npm run start:reset
ports:
  - port: 8081
    onOpen: ignore

