tasks:
  - init: npm ci
    command: npm run start:reset
  - command: gp await-port 8081 && sleep 5 && gp preview $(gp url 8081)/index.bundle?dev=true&minify=false&platform=android &
  - command: gp await-port 8081 && sleep 5 && gp preview $(gp url 8081)/index.bundle?dev=true&minify=false&platform=ios &
ports:
  - port: 8081
    onOpen: ignore

